apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-08-26T21:46:46Z
  labels:
    app: helloworld
  name: helloworld-service
  namespace: default
  resourceVersion: "1305"
  selfLink: /api/v1/namespaces/default/services/helloworld-service
  uid: 8758b3a3-a979-11e8-b69f-42010a980027
spec:
  clusterIP: 10.51.248.37
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31724
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloworld
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.189.16.19
