apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-26T21:45:26Z
  generation: 5
  labels:
    app: helloworld
  name: helloworld
  namespace: default
  resourceVersion: "2217"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/helloworld
  uid: 57b3871e-a979-11e8-b69f-42010a980027
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
      - image: lammerse/flask-helloworld:latest
        imagePullPolicy: Always
        name: flask-helloworld
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-08-26T21:57:57Z
    lastUpdateTime: 2018-08-26T21:57:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
